version: 2.0.0-beta+{build}
branches:
  only:
  - master
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
os: Visual Studio 2015
install:
- git submodule update --init --recursive
before_build:
- nuget restore
build:
  project: Stoffi.sln
notifications:
- provider: Slack
  auth_token:
    secure: ZIZ1ZE+PiJy00kpkOs/50Cgnn1y/U65Hs5xV9eYdyvnDi0tItUUd0y3DnS4l/mld
  channel: '#general'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
