version: 1.50.0-beta+{build}
branches:
  only:
  - master
  - develop
install:
- git submodule update --init --recursive
before_build:
- cp Core\Services\Keys.tmpl.cs Core\Services\Keys.cs
build:
  project: GUI\Stoffi for Windows.csproj
  verbosity: detailed
notifications:
- provider: Slack
  auth_token:
    secure: ZIZ1ZE+PiJy00kpkOs/50Cgnn1y/U65Hs5xV9eYdyvnDi0tItUUd0y3DnS4l/mld
  channel: stoffi
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true