version: 2.0.0-beta+{build}
branches:
  only:
  - master
  - develop
os: Visual Studio 2015 RC
install:
- git submodule update --init --recursive
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  project: Stoffi.csproj
  verbosity: detailed
notifications:
- provider: Slack
  auth_token:
    secure: ZIZ1ZE+PiJy00kpkOs/50Cgnn1y/U65Hs5xV9eYdyvnDi0tItUUd0y3DnS4l/mld
  channel: stoffi
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true